# 워크플로우의 이름 지정
name: CI

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches: [featrue/spring/branch]

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정
    # 실행 스템 지정
    steps:
      - uses: actions/checkout@v3 # 코드 체크아웃

      - uses: actions/setup-java@v3 # Java 설정
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew clean build