/*
 * This source file was generated by the Gradle 'init' task
 */
package tobyspring;

import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        
    }
}
